#include <cstdlib>
#include <ctime>
#include <iostream>
#include <time.h>
#include <stdexcept>
#include <iomanip>
#include <fstream>
#include <cmath>
#include <vector>
#include <stack>
#include <string>
#include <unordered_map>
#include <math.h>
#include <random>
#include <chrono>
#include <unordered_set>
#include <sstream>
#include <filesystem>
#include <iomanip>
#include <SFML/Graphics.hpp>
#include <SFML/System.hpp>
#include <SFML/Audio.hpp>
#include <SFML/Network.hpp>
#include <SFML/Window.hpp>